
<field:lybt itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lybt>

<field:nr itemname="留言内容" autofield="1" type="textchar" isnull="true" default=""  maxlength="1000" page="">
</field:nr>

<field:youxiang itemname="联系邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:youxiang>

<field:dhhm itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dhhm>

<field:lxr itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxr>
