<?php
$z[0]=Array("global","",100,127);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",139,166);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",245,272);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li> \r\n    ",292,409);
$z[3][4]['row']="4";
$z[3][4]['type']="top";
$z[4]=Array("global","",482,509);
$z[4][4]['name']="cfg_basehost";

?>